version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # pom.xml en raíz
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/" # workflows
    schedule:
      interval: "weekly"
