name: Build and Push to ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Requisitos antes de ejecutar:
# - Configura OIDC en Azure AD para este repo (App Registration + Federated Credentials)
# - Crea los siguientes secrets en GitHub (repo > Settings > Secrets and variables > Actions):
#   AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID
# - Crea variables de repo (Settings > Secrets and variables > Actions > Variables):
#   ACR_NAME (p.ej. miacr), ACR_LOGIN_SERVER (p.ej. miacr.azurecr.io), ACR_REPOSITORY (p.ej. poc-maven-azure-app)

env:
  ACR_NAME: ${{ vars.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
  ACR_REPOSITORY: ${{ vars.ACR_REPOSITORY }}
  IMAGE_TAG_SHA: ${{ github.sha }}
  IMAGE_TAG_LATEST: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # requerido para OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Si el SP no tiene Reader a nivel de suscripción, descomenta:
          # allow-no-subscriptions: true

      - name: Normalize ACR name and verify
        shell: bash
        run: |
          echo "Inputs -> ACR_NAME='$ACR_NAME' ACR_LOGIN_SERVER='$ACR_LOGIN_SERVER'" | sed 's/\r//'

          # Normaliza el nombre del ACR (sin protocolo ni dominio)
          to_name_only() {
            local s="$1"
            # a minúsculas, sin protocolo, sin ruta, sin dominio
            s="${s,,}"
            s="${s#http://}"
            s="${s#https://}"
            s="${s%%/*}"
            s="${s%%.*}"
            echo "$s"
          }

          ACR_NAME_TRIM=$(to_name_only "$ACR_NAME")
          ACR_LOGIN_FROM_SERVER=$(to_name_only "$ACR_LOGIN_SERVER")

          if [[ -n "$ACR_NAME_TRIM" && "$ACR_NAME_TRIM" =~ ^[a-z0-9]+$ ]]; then
            ACR_NAME_NORM="$ACR_NAME_TRIM"
          else
            ACR_NAME_NORM="$ACR_LOGIN_FROM_SERVER"
          fi

          # Validación básica
          LEN=${#ACR_NAME_NORM}
          if [[ $LEN -lt 5 || $LEN -gt 50 || ! "$ACR_NAME_NORM" =~ ^[a-z0-9]+$ ]]; then
            echo "ACR_NAME_NORM calculado inválido: '$ACR_NAME_NORM'" >&2
            echo "Asegúrate de definir ACR_NAME (solo nombre) o ACR_LOGIN_SERVER (p.ej. miacr.azurecr.io)" >&2
            exit 1
          fi

          echo "ACR_NAME_NORM=$ACR_NAME_NORM" >> "$GITHUB_ENV"
          echo "Using registry: $ACR_NAME_NORM" >> $GITHUB_STEP_SUMMARY
          az account show -o table
          az acr show -n "$ACR_NAME_NORM" -o table

      # Construcción en servidor con ACR Tasks (no requiere Docker en el runner)
      - name: Build and push image (ACR Tasks)
        run: |
          az acr build \
            -r "$ACR_NAME_NORM" \
            -t "$ACR_REPOSITORY:$IMAGE_TAG_SHA" \
            -t "$ACR_REPOSITORY:$IMAGE_TAG_LATEST" \
            .

      - name: Summary
        run: |
          echo "Pushed: $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$IMAGE_TAG_SHA" >> $GITHUB_STEP_SUMMARY
          echo "Pushed: $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$IMAGE_TAG_LATEST" >> $GITHUB_STEP_SUMMARY
