name: PR Quality & Security

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven


    #### --- OPA/Conftest: exige USER no root en Dockerfile ---
      - name: Install Conftest
        run: |
          wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.49.0/conftest_0.49.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.49.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Enforce non-root user in Dockerfile
        run: conftest test Dockerfile --policy policy/ --parser dockerfile
      - name: Build and test
        run: mvn -B clean verify -DskipTests=false

      - name: OWASP Dependency Check with Maven
        run: |
          mvn org.owasp:dependency-check-maven:10.0.4:check \
            -DfailBuildOnCVSS=0 \
            -DsuppressFailureOnExit=true \
            -Dformat=ALL \
            -DprettyPrint=true
        continue-on-error: true

      - name: Upload OWASP reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-reports
          path: target/dependency-check-report.*
          retention-days: 30

      - name: Trivy table output (visible)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
        continue-on-error: true

      - name: Trivy SARIF output (for GitHub Security)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
        continue-on-error: true

      - name: Upload Trivy SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
        continue-on-error: true

      - name: Security Summary with Details
        if: always()
        run: |
          echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "### Trivy Results" >> $GITHUB_STEP_SUMMARY
          if [ -f "trivy-results.sarif" ]; then
            echo "- Trivy scan completed - check Security tab for details" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Trivy scan failed" >> $GITHUB_STEP_SUMMARY
          fi
          echo "### OWASP Results" >> $GITHUB_STEP_SUMMARY
          if [ -f "target/dependency-check-report.html" ]; then
            echo "- OWASP Maven plugin scan completed - check artifacts for download" >> $GITHUB_STEP_SUMMARY
            echo "- Report files generated:" >> $GITHUB_STEP_SUMMARY
            ls -la target/dependency-check-report.* 2>/dev/null | while read line; do echo "  - ${line##*/}" >> $GITHUB_STEP_SUMMARY; done || true
          else
            echo "- OWASP scan failed or no reports generated" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note**: All security checks are informational and do not block PR merges" >> $GITHUB_STEP_SUMMARY